<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKclLIwD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKclLIwD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKclLIwD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKclLIwD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKclLIwD\App_KernelDevDebugContainer([
    'container.build_hash' => 'KclLIwD',
    'container.build_id' => '587234a3',
    'container.build_time' => 1703630906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKclLIwD');
