<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_landing' => [[], ['_controller' => 'App\\Controller\\ExceptionController::landing'], [], [['text', '/']], [], [], []],
    'errorCode' => [['statusCode'], ['_controller' => 'App\\Controller\\ExceptionController::showException'], ['statusCode' => '\\d+'], [['variable', '/', '\\d+', 'statusCode', true], ['text', '/error']], [], [], []],
    'privacy' => [[], ['_controller' => 'App\\Controller\\ExceptionController::privacy'], [], [['text', '/privacy_policy']], [], [], []],
    'conditionEtTerme' => [[], ['_controller' => 'App\\Controller\\ExceptionController::terme'], [], [['text', '/termes/conditions']], [], [], []],
    'app_register_admin' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register_admin'], [], [['text', '/user/register/admin']], [], [], []],
    'app_register_agent' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register_agent'], [], [['text', '/user/register/agent']], [], [], []],
    'app_register_client' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register_client'], [], [['text', '/user/register/client']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/security/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/security/logout']], [], [], []],
    'app_ticket_index_all' => [[], ['_controller' => 'App\\Controller\\TicketController::indexAll'], [], [['text', '/user/ticket/all']], [], [], []],
    'app_ticket_index' => [[], ['_controller' => 'App\\Controller\\TicketController::index'], [], [['text', '/user/ticket/']], [], [], []],
    'app_ticket_new' => [[], ['_controller' => 'App\\Controller\\TicketController::new'], [], [['text', '/user/ticket/new']], [], [], []],
    'app_ticket_show' => [['id'], ['_controller' => 'App\\Controller\\TicketController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/ticket/show']], [], [], []],
    'app_ticket_edit' => [['id'], ['_controller' => 'App\\Controller\\TicketController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/ticket/edit']], [], [], []],
    'app_ticket_delete' => [['id'], ['_controller' => 'App\\Controller\\TicketController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/ticket']], [], [], []],
    'app_user_admin_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/admin/hghf455c4/dashboard/ohhyes']], [], [], []],
    'app_user_agent_index' => [[], ['_controller' => 'App\\Controller\\UserController::indexAgent'], [], [['text', '/user/agent/hghcnhgn/4c5dr656v/dashboard/ohhyes']], [], [], []],
    'app_user_client_index' => [[], ['_controller' => 'App\\Controller\\UserController::indexClient'], [], [['text', '/user/client/hbchgcg543m/767btr/dashboard/ohhyes']], [], [], []],
    'app_user_new' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/user/jbhjb/jhjhbjh/new/jbjbbjbjkbk']], [], [], []],
    'app_user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['text', 'k/bcccjbkch6736hjh36'], ['variable', '', '[^/]+', 'id', true], ['text', '/user/ghfxgfxb/show/nwlsnckcaklcn/nlancl']], [], [], []],
    'app_user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', 'kbcc98ah/vhv56ch6736hjh36'], ['variable', '', '[^/]+', 'id', true], ['text', '/user/edit/nwlkjcbhdbjhklcnwj/njnsnlancl']], [], [], []],
    'app_user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['text', 'kbcccjbkch6736hjh36'], ['variable', '', '[^/]+', 'id', true], ['text', '/user/nwlsnckcaklcnsjdnksbvhwjnjnsnlancl']], [], [], []],
    'app_table_view' => [[], ['_controller' => 'App\\Controller\\UserController::tableAgent'], [], [['text', '/user/vbvbv/nb/table/bjbvjs74/vsj7887agent/kvsjfkb']], [], [], []],
    'app_user_client_ticket' => [[], ['_controller' => 'App\\Controller\\UserController::clientTicket'], [], [['text', '/user/client/ticket']], [], [], []],
    'app_user_agent_ticket' => [[], ['_controller' => 'App\\Controller\\UserController::agentTicket'], [], [['text', '/user/agent/ticket']], [], [], []],
    'retour' => [[], ['_controller' => 'App\\Controller\\UserController::retour'], [], [['text', '/user']], [], [], []],
];
